// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmnJGgUsxgMF315c4lXsvC5go6vdoojhU',
    appId: '1:762839524110:web:60d713fe9b0e9600d0ed5f',
    messagingSenderId: '762839524110',
    projectId: 'flutter-238b6',
    authDomain: 'flutter-238b6.firebaseapp.com',
    storageBucket: 'flutter-238b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLofZU0vae49cl128ypyszigqkxP-jDo',
    appId: '1:762839524110:android:5d1d10558ab81148d0ed5f',
    messagingSenderId: '762839524110',
    projectId: 'flutter-238b6',
    storageBucket: 'flutter-238b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_BbUPydbqxBla1vz_ssgdflnPn8uSxN4',
    appId: '1:762839524110:ios:9aed85d977084dfcd0ed5f',
    messagingSenderId: '762839524110',
    projectId: 'flutter-238b6',
    storageBucket: 'flutter-238b6.appspot.com',
    iosBundleId: 'com.example.youtubeUm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_BbUPydbqxBla1vz_ssgdflnPn8uSxN4',
    appId: '1:762839524110:ios:9aed85d977084dfcd0ed5f',
    messagingSenderId: '762839524110',
    projectId: 'flutter-238b6',
    storageBucket: 'flutter-238b6.appspot.com',
    iosBundleId: 'com.example.youtubeUm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmnJGgUsxgMF315c4lXsvC5go6vdoojhU',
    appId: '1:762839524110:web:3b427f45ab6cb591d0ed5f',
    messagingSenderId: '762839524110',
    projectId: 'flutter-238b6',
    authDomain: 'flutter-238b6.firebaseapp.com',
    storageBucket: 'flutter-238b6.appspot.com',
  );
}
